# Generated by Django 5.1.1 on 2024-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Total_Hours', models.TimeField()),
                ('Checked_In', models.BooleanField(default=False)),
                ('Total_Seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]