# Generated by Django 5.1.1 on 2024-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Total_Seconds',
            field=models.FloatField(default=0),
        ),
    ]