# Generated by Django 5.1.1 on 2024-09-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0002_alter_users_total_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Last_In',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Last_Out',
            field=models.DateTimeField(null=True),
        ),
    ]