# Generated by Django 5.1.1 on 2024-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0003_users_last_in_users_last_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Last_In',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Last_Out',
            field=models.DateTimeField(null=True),
        ),
    ]