# Generated by Django 5.1.1 on 2024-09-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0004_alter_users_last_in_alter_users_last_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Total_Hours',
            field=models.TimeField(),
        ),
    ]