# Generated by Django 5.1.1 on 2024-09-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0006_alter_users_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Total_Hours',
            field=models.TimeField(),
        ),
    ]