# Generated by Django 5.1.1 on 2024-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0007_alter_users_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('checkIn', 'Check In'), ('checkOut', 'Check Out')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=8)),
                ('message', models.TextField(default='None')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='Total_Hours',
            field=models.TimeField(),
        ),
    ]