# Generated by Django 5.1.1 on 2024-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0008_activitylog_alter_users_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(default=''),
        ),
    ]