# Generated by Django 5.1.1 on 2024-10-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0009_alter_activitylog_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-id']},
        ),
    ]