# Generated by Django 5.1.2 on 2024-10-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0010_alter_activitylog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20),
        ),
    ]