# Generated by Django 5.1.2 on 2024-10-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0011_alter_activitylog_options_alter_activitylog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Members', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='operation',
            field=models.CharField(choices=[('checkIn', 'Check In'), ('checkOut', 'Check Out'), ('none', 'None')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('user not found', 'User Not Found')], max_length=20),
        ),
    ]