# Generated by Django 5.1.2 on 2024-10-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0013_alter_activitylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Is_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('user not found', 'User Not Found'), ('inactive user', 'Inactive User')], max_length=20),
        ),
    ]