# Generated by Django 5.1.2 on 2024-10-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0014_users_is_active_alter_activitylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Last_In',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]