# Generated by Django 5.1.2 on 2024-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0015_alter_users_last_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Total_Hours',
            field=models.DurationField(),
        ),
    ]