# Generated by Django 5.1.2 on 2026-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0018_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='operation',
            field=models.CharField(choices=[('checkIn', 'Check In'), ('checkOut', 'Check Out'), ('none', 'None'), ('autoCheckOut', 'Auto Check Out')], max_length=14),
        ),
    ]