# Generated by Django 5.2.9 on 2026-01-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0019_alter_activitylog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Last_In',
            field=models.DateTimeField(null=True),
        ),
    ]