# Generated by Django 5.2.9 on 2026-02-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0020_alter_users_last_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='operation',
            field=models.CharField(choices=[('Check In', 'Check In'), ('Check Out', 'Check Out'), ('None', 'None'), ('Auto Check Out', 'Auto Check Out'), ('Reset', 'Reset')], max_length=15),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('User Not Found', 'User Not Found'), ('Inactive User', 'Inactive User')], max_length=20),
        ),
    ]
