# Generated by Django 5.2.11 on 2026-02-15 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroHours', '0021_alter_activitylog_operation_alter_activitylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='HeroHours.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Last_In',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Last_Out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Total_Seconds',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='HeroHours_a_timesta_b5495e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='HeroHours_a_user_id_cb5e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['operation', 'status'], name='HeroHours_a_operati_d5bf01_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['Last_Name', 'First_Name'], name='Users_Last_Na_e25c91_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['Checked_In'], name='Users_Checked_6fa301_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['Is_Active'], name='Users_Is_Acti_bc9d4d_idx'),
        ),
    ]
